# GoReleaser configuration for glcron
# Run: goreleaser release --clean
# Test: goreleaser release --snapshot --clean

version: 2
project_name: glcron

builds:
  - id: glcron
    main: ./cmd/glcron
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'glcron/internal/tui.AppVersion={{ .Version }}'

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

homebrews:
  - name: glcron
    homepage: "https://github.com/nikitasova/glcron"
    description: "A TUI tool for managing GitLab CI/CD pipeline schedules"
    url_template: "https://github.com/nikitasova/glcron/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    test: |
      system "#{bin}/glcron --version"
    install: |
      bin.install "glcron"
    repository:
      owner: nikitasova
      name: homebrew-glcron
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"

nfpms:
  - id: glcron-deb
    package_name: glcron
    vendor: nikitasova
    homepage: "https://github.com/nikitasova/glcron"
    maintainer: nikitasova <nikitasova@users.noreply.github.com>
    description: "A TUI tool for managing GitLab CI/CD pipeline schedules"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: LICENSE
        dst: /usr/share/doc/glcron/LICENSE
      - src: README.md
        dst: /usr/share/doc/glcron/README.md

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: '⚠️ Breaking Changes'
      regexp: "^.*!:.+$"
      order: 0
    - title: '✨ Features'
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 1
    - title: '🐛 Bug Fixes'
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 2
    - title: '⚡️ Improvements'
      regexp: "^.*perf[(\\w)]*:.*$"
      order: 3
